# Generated by Django 2.0.2 on 2018-02-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='call',
            fields=[
                ('callid', models.IntegerField(primary_key=True, serialize=False)),
                ('sentiment', models.CharField(max_length=10)),
                ('summary', models.CharField(max_length=500)),
                ('service_provider', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('ccid', models.IntegerField()),
                ('text', models.TextField(max_length=1000)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('total_calls', models.IntegerField()),
                ('total_minutes', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('sentiment', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
