# Generated by Django 2.0.2 on 2018-02-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180210_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='summary',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='rating',
            new_name='total_seconds',
        ),
        migrations.RemoveField(
            model_name='call',
            name='time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_minutes',
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
